package org.radarbase.appserver.service

import jakarta.inject.Inject
import jakarta.inject.Named
import jakarta.ws.rs.core.Context
import org.radarbase.appserver.dto.ProjectDto
import org.radarbase.appserver.dto.ProjectDtos
import org.radarbase.appserver.enhancer.AppserverResourceEnhancer.Companion.PROJECT_MAPPER
import org.radarbase.appserver.entity.Project
import org.radarbase.appserver.exceptions.AlreadyExistsException
import org.radarbase.appserver.mapper.Mapper
import org.radarbase.appserver.mapper.ProjectMapper
import org.radarbase.appserver.repository.ProjectRepository
import org.radarbase.appserver.utils.checkInvalidProjectDetails
import org.radarbase.appserver.utils.checkPresence
import org.slf4j.LoggerFactory

/**
 * Service class for managing projects.
 *
 * [Projects][Project] represent the same entities as in the [ManagementPortal](https://github.com/RADAR-base/ManagementPortal) and their names
 * should align with the projects in the [ManagementPortal](https://github.com/RADAR-base/ManagementPortal).
 *
 * It uses [ProjectRepository] for persistence operations and [ProjectMapper]
 * for converting between entity and DTO objects.
 */
@Suppress("unused")
class ProjectService @Inject constructor(
    private val projectRepository: ProjectRepository,
    @Named(PROJECT_MAPPER) private val projectMapper: Mapper<ProjectDto, Project>,
) {
    init {
        logger.info(
            "Project Service: Repository: {} Mapper: {}",
            projectRepository::class.simpleName,
            projectRepository::class.simpleName,
        )
    }

    /**
     * Retrieves all projects from the repository.
     *
     * @return [ProjectDtos] object containing a list of all projects as DTOs.
     */
    suspend fun getAllProjects(): ProjectDtos {
        return ProjectDtos(projectMapper.entitiesToDtos(projectRepository.all()).toMutableList())
    }

    /**
     * Retrieves a project by its unique identifier (ID).
     *
     * @param id the unique ID of the project
     * @return the [ProjectDto] of the project
     * @throws org.radarbase.jersey.exception.HttpNotFoundException if no project with the given ID exists
     */
    suspend fun getProjectById(id: Long): ProjectDto {
        val project: Project = checkPresence(projectRepository.get(id), "project_not_found") {
            "Project with id $id not found"
        }

        return projectMapper.entityToDto(project)
    }

    /**
     * Retrieves a project by its ManagementPortal project ID.
     *
     * @param projectId the unique project ID in the ManagementPortal
     * @return the [ProjectDto] of the project
     * @throws org.radarbase.jersey.exception.HttpNotFoundException if no project with the given project ID exists
     */
    suspend fun getProjectByProjectId(projectId: String): ProjectDto {
        val project = checkPresence(
            projectRepository.getByProjectId(projectId),
            "project_not_found",
        ) { "Project with projectId $projectId not found" }

        return projectMapper.entityToDto(project)
    }

    /**
     * Creates a new project in the repository.
     *
     * @param projectDTO the [ProjectDto] containing details of the project to create
     * @return the [ProjectDto] of the newly created project
     * @throws org.radarbase.appserver.exceptions.InvalidProjectDetailsException if the input contains invalid data
     * @throws org.radarbase.appserver.exceptions.AlreadyExistsException if the project is already present
     */
    suspend fun addProject(projectDTO: ProjectDto): ProjectDto {
        val projectId: String? = projectDTO.projectId

        logger.info("Adding project with id $projectId adding to project")

        checkInvalidProjectDetails(
            projectDTO,
            { projectDTO.id != null },
            { "'id' must not be supplied when creating a project, it is autogenerated" },
        )

        checkInvalidProjectDetails(
            projectDTO,
            { projectId == null },
            { "At least 'project id' must be supplied" },
        )

        if (projectRepository.existsByProjectId(projectId!!)) {
            throw AlreadyExistsException(
                "project_already_exists",
                "The project with specified project-id (${projectDTO.projectId}) already exists. Use Update endpoint if need to update the project.",
            )
        }

        return projectMapper.entityToDto(projectRepository.add(projectMapper.dtoToEntity(projectDTO))).also {
            logger.info("Project ${projectId} added to project")
        }
    }

    /**
     * Updates an existing project in the repository.
     *
     * @param projectDTO the [ProjectDto] containing updated details of the project
     * @return the updated [ProjectDto]
     * @throws org.radarbase.appserver.exceptions.InvalidProjectDetailsException if the input contains invalid project data
     * @throws org.radarbase.jersey.exception.HttpNotFoundException if the project to update does not exist
     */
    suspend fun updateProject(projectDTO: ProjectDto): ProjectDto {
        checkInvalidProjectDetails(
            projectDTO,
            { projectDTO.id == null },
            { "The 'id' of the project must be supplied for updating project" },
        )

        val existingProject: Project = checkPresence(
            projectRepository.get(projectDTO.id!!),
            "project_not_found",
        ) { "Project with id ${projectDTO.id} not found" }

        val savedProject = projectRepository.add(existingProject.apply { this.projectId = projectDTO.projectId })

        return projectMapper.entityToDto(savedProject)
    }

    companion object {
        private val logger = LoggerFactory.getLogger(ProjectService::class.java)
    }
}
