/*
 * Copyright 2025 King's College London
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.radarbase.appserver.microservices.contract.utils

object Env {
    const val PROJECT_SERVICE_BASE_URL = "APPSERVER_PROJECT_SERVICE_BASE_URL"
    const val USER_SERVICE_BASE_URL = "APPSERVER_USER_SERVICE_BASE_URL"
    const val GATEWAY_SERVICE_BASE_URL = "APPSERVER_GATEWAY_SERVICE_BASE_URL"
    const val GITHUB_SERVICE_BASE_URL = "APPSERVER_GITHUB_SERVICE_BASE_URL"
    const val PROTOCOL_SERVICE_BASE_URL = "APPSERVER_PROTOCOL_SERVICE_BASE_URL"
    const val TASK_STATE_EVENT_SERVICE_BASE_URL = "APPSERVER_TASK_STATE_EVENT_SERVICE_BASE_URL"

    const val APPSERVER_TASK_STATE_EVENT_PREFIX = "APPSERVER_TASK_STATE_EVENT"
    const val TASK_STATE_EVENT_JDBC_URL = "${APPSERVER_TASK_STATE_EVENT_PREFIX}_JDBC_URL"
    const val TASK_STATE_EVENT_JDBC_USERNAME = "${APPSERVER_TASK_STATE_EVENT_PREFIX}_JDBC_USERNAME"
    const val TASK_STATE_EVENT_JDBC_PASSWORD = "${APPSERVER_TASK_STATE_EVENT_PREFIX}_JDBC_PASSWORD"
    const val TASK_STATE_EVENT_HIBERNATE_DIALECT = "${APPSERVER_TASK_STATE_EVENT_PREFIX}_HIBERNATE_DIALECT"
    const val TASK_STATE_EVENT_JDBC_DRIVER = "${APPSERVER_TASK_STATE_EVENT_PREFIX}_JDBC_DRIVER"

    const val APPSERVER_PROJECT_PREFIX = "APPSERVER_PROJECT"
    const val PROJECT_JDBC_URL = "${APPSERVER_PROJECT_PREFIX}_JDBC_URL"
    const val PROJECT_JDBC_USERNAME = "${APPSERVER_PROJECT_PREFIX}_JDBC_USERNAME"
    const val PROJECT_JDBC_PASSWORD = "${APPSERVER_PROJECT_PREFIX}_JDBC_PASSWORD"
    const val PROJECT_HIBERNATE_DIALECT = "${APPSERVER_PROJECT_PREFIX}_HIBERNATE_DIALECT"
    const val PROJECT_JDBC_DRIVER = "${APPSERVER_PROJECT_PREFIX}_JDBC_DRIVER"

    const val APPSERVER_USER_PREFIX = "APPSERVER_USER"
    const val USER_JDBC_URL = "${APPSERVER_USER_PREFIX}_JDBC_URL"
    const val USER_JDBC_USERNAME = "${APPSERVER_USER_PREFIX}_JDBC_USERNAME"
    const val USER_JDBC_PASSWORD = "${APPSERVER_USER_PREFIX}_JDBC_PASSWORD"
    const val USER_HIBERNATE_DIALECT = "${APPSERVER_USER_PREFIX}_HIBERNATE_DIALECT"
    const val USER_JDBC_DRIVER = "${APPSERVER_USER_PREFIX}_JDBC_DRIVER"

}
