# start the supporting dockerstack using the :dev image of the managementportal dependency.
version: "3.8"

include:
  - "../non_appserver/docker-compose.yml"

# This file should be called in conjunction with the accompanying docker-compose.override.yml file
# This can be done by navigating to the directory with both files and calling 'docker compose up -d'