# start the dockerstack using a prebuilt image pulled from dockerhub. This stack does not work without adding GOOGLE_APPLICATION_CREDENTIALS
version: "3.8"

include:
  - "../non_appserver/docker-compose.yml"

services:
  appserver:
    extends:
      file: ../appserver.yml
      service: appserver
    networks:
      - db
      - default
      - admin