version: '2.1'

networks:
  db:
    driver: bridge
    internal: true
  admin:
    driver: bridge
    internal: true
  mp:
    driver: bridge
    internal: true
  ext:
    driver: bridge
    internal: false

services:
  postgres:
    image: postgres
    restart: always
    networks:
      - db
      - default
      - ext
    environment:
      POSTGRES_DB: radar
      POSTGRES_PASSWORD: radar
    ports:
      - "5432:5432"

  appserver:
    build: ../../../..
    restart: always
    networks:
      - db
      - default
      - admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - spring-boot-admin
    volumes:
      - ../radar-is.yml:/resources/radar-is.yml
      - ../../../../logs/:/var/log/radar/appserver/
    environment:
      JDK_JAVA_OPTIONS: -Xmx4G -Djava.security.egd=file:/dev/./urandom
      FCMSERVER_SENDERID: "1043784930865"
      FCMSERVER_SERVERKEY: "AAAA8wZuFjE:APA91bGpJQ3Sft0mZAaVMjDJGNLjFsdDLTo-37ZN69r4lKlHiRN78t4bCfkNKcXG5c9cJg-eGtWB7FqceQUDVtf7B1Zvw_2ycynqwKe2YqXFeyaq83Gf0R3AS1EKSWFS60GCr8eUEliz"
      RADAR_ADMIN_USER: "radar"
      RADAR_ADMIN_PASSWORD: "radar"
      SPRING_APPLICATION_JSON: '{"spring":{"boot":{"admin":{"client":{"url":"http://spring-boot-admin:1111","username":"radar","password":"appserver"}}}}}'
      RADAR_IS_CONFIG_LOCATION: "/resources/radar-is.yml"
      SPRING_BOOT_ADMIN_CLIENT_INSTANCE_NAME: radar-appserver

  spring-boot-admin:
    image: slydeveloper/spring-boot-admin:latest
    restart: always
    networks:
      - admin
      - default
    ports:
      - "8888:1111"
    environment:
      SPRING_BOOT_ADMIN_USER_NAME: radar
      SPRING_BOOT_ADMIN_USER_PASSWORD: appserver
      SPRING_BOOT_ADMIN_TITLE: RADAR-appserver
      SPRING_APPLICATION_JSON: '{"spring":{"boot":{"admin":{"username":"radar","password":"appserver","title":"RADAR-appserver"}}}}'

  #---------------------------------------------------------------------------#
  # Management Portal                                                         #
  #---------------------------------------------------------------------------#
  managementportal:
#    image: managementportal:latest
    image: radarbase/management-portal:dev
    depends_on:
      - managementportal-postgresql
    networks:
      - mp
      - ext
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://managementportal-postgresql:5432/managementportal
      SPRING_DATASOURCE_USERNAME: radarbase
      SPRING_DATASOURCE_PASSWORD: radarbase
      SPRING_LIQUIBASE_CONTEXTS: dev #includes testing_data, remove for production builds
      MANAGEMENTPORTAL_FRONTEND_CLIENT_SECRET: ""
      MANAGEMENTPORTAL_COMMON_BASE_URL: http://localhost:8081/managementportal
      MANAGEMENTPORTAL_COMMON_MANAGEMENT_PORTAL_BASE_URL: http://localhost:8081/managementportal
      MANAGEMENTPORTAL_OAUTH_CLIENTS_FILE: /mp-includes/config/oauth_client_details.csv
      JHIPSTER_SLEEP: 10 # gives time for the database to boot before the application
      JAVA_OPTS: -Xmx512m  # maximum heap size for the JVM running ManagementPortal, increase this as necessary
    ports:
      - "8081:8081"
    volumes:
      - ./etc:/mp-includes

  managementportal-postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: radarbase
      POSTGRES_PASSWORD: radarbase
      POSTGRES_DB: managementportal
    networks:
      - mp