name: Snyk scheduled Docker image scan
on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: radarbase/radar-appserver
          args: |
            --file=Dockerfile
            --all-projects
            --org=radar-base
            --fail-on=upgradable
            --severity-threshold=high
            --json-file-output=snyk.json
            --policy-path=$PWD/.snyk

      - name: Report new vulnerabilities
        uses: thehyve/report-vulnerability@master
        if: success() || failure()
        with:
          report-file: snky.json
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
